In [2]:

pip install fiona

Requirement already satisfied: fiona in /Users/stephensmathew/anaconda3/envs/testenv/lib/python3.9/site-packages (1.10.1)
Requirement already satisfied: attrs>=19.2.0 in /Users/stephensmathew/anaconda3/envs/testenv/lib/python3.9/site-packages (from fiona) (25.3.0)
Requirement already satisfied: certifi in /Users/stephensmathew/anaconda3/envs/testenv/lib/python3.9/site-packages (from fiona) (2024.8.30)
Requirement already satisfied: click~=8.0 in /Users/stephensmathew/anaconda3/envs/testenv/lib/python3.9/site-packages (from fiona) (8.1.8)
Requirement already satisfied: click-plugins>=1.0 in /Users/stephensmathew/anaconda3/envs/testenv/lib/python3.9/site-packages (from fiona) (1.1.1)
Requirement already satisfied: cligj>=0.5 in /Users/stephensmathew/anaconda3/envs/testenv/lib/python3.9/site-packages (from fiona) (0.7.2)
Requirement already satisfied: importlib-metadata in /Users/stephensmathew/anaconda3/envs/testenv/lib/python3.9/site-packages (from fiona) (8.5.0)
Requirement already satisfied: zipp>=3.20 in /Users/stephensmathew/anaconda3/envs/testenv/lib/python3.9/site-packages (from importlib-metadata->fiona) (3.21.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import fiona
import geopandas as gpd
import pandas as pd
import numpy as np
import regex as re
import os

In [ ]:

file_path = "/Users/stephensmathew/cdl_rep/flood-data-ecosystem-UP/Maps/up_ids-drr_shapefiles/UP_Subdistrict_final_modified.geojson"

In [5]:
od_block = gpd.read_file(file_path)
od_block.set_crs(epsg=32644, inplace=True, allow_override=True)
print(od_block.crs)
od_block = od_block.to_crs(epsg=4326)
print(od_block.crs)
od_block

EPSG:32644
EPSG:4326

,object_id,stname,dtname,sdtname,st_area_sh,st_length_,remarks,dist_lgd,state_lgd,subdt_lgd,ac_no,st_length(shape),st_area(shape),geometry
0,09-168-00865,UTTAR PRADESH,Hamirpur,Rath,0.0,0.0,,149,9,865,229,205155.793938,9.132342e+08,"MULTIPOLYGON (((143.40405 13.08949, 143.40435 ..."
1,09-200-01005,UTTAR PRADESH,Sonbhadra,Robertsganj,0.0,0.0,,184,9,1005,401,445254.946921,4.053319e+09,"MULTIPOLYGON (((144.88699 11.95762, 144.88745 ..."
2,09-177-00902,UTTAR PRADESH,Ayodhya,Rudauli,0.0,0.0,,140,9,902,271,209118.573449,7.294307e+08,"MULTIPOLYGON (((144.7361 13.14372, 144.7361 13..."
3,09-185-00940,UTTAR PRADESH,Basti,Rudhauli,0.0,0.0,,131,9,940,309,156884.643689,2.995772e+08,"MULTIPOLYGON (((145.24035 13.03016, 145.24036 ..."
4,09-190-00960,UTTAR PRADESH,Deoria,Rudrapur,0.0,0.0,,137,9,960,336,182005.111691,4.947448e+08,"MULTIPOLYGON (((145.50905 12.62267, 145.50985 ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,09-139-00737,UTTAR PRADESH,Baghpat,Khekada,0.0,0.0,,124,9,737,52,99117.973402,2.436437e+08,"MULTIPOLYGON (((143.18647 15.19522, 143.18701 ..."
312,09-137-00718,UTTAR PRADESH,Amroha,Kanth,0.0,0.0,,154,9,718,25,164751.224731,3.896811e+08,"MULTIPOLYGON (((143.89582 14.98745, 143.89596 ..."
313,09-202-01011,UTTAR PRADESH,Kasganj,Sahawar,0.0,0.0,,633,9,1011,101,227960.411531,5.795948e+08,"MULTIPOLYGON (((143.66052 14.30519, 143.66064 ..."
314,09-178-00911,UTTAR PRADESH,Ambedkar Nagar,Bhiti,0.0,0.0,,121,9,911,277,168213.889736,3.854525e+08,"MULTIPOLYGON (((144.93483 12.88404, 144.93504 ..."
315,09-173-00884,UTTAR PRADESH,Pratapgarh,Raniganj,0.0,0.0,,174,9,884,250,159943.826905,5.281397e+08,"MULTIPOLYGON (((144.64996 12.62932, 144.6502 1..."

In [6]:
up_vil_unfiltered = gpd.read_file("/Users/stephensmathew/cdl_rep/flood-data-ecosystem-UP/Maps/up_ids-drr_shapefiles/UP_Villages_Boundary_Simplified.zip")
up_vil_unfiltered

,objectid,vilnam_soi,stcode11,dtcode11,sdtcode11,vilcode11,stname,dtname,sdtname,vilname11,...,gp_name,subdt_lgd,block_name,block_lgd,remark,ac_no,search_village,st_length(shape),st_area(shape),geometry
0,442063,RF,09,146,00770,,UTTAR PRADESH,Agra,Bah,,...,,770,JAITPUR KALAN,812,None,94,", Bah,Agra,UTTAR PRADESH",1831.228208,8.618876e+04,"POLYGON ((8761215.3837 3100427.7461, 8761038.7..."
1,447787,KUCHELA,09,162,00841,148028,UTTAR PRADESH,Auraiya,Bidhuna,Kuchela,...,KUKARKAT,841,ERWA KATRA,864,None,202,"Kuchela , Bidhuna,Auraiya,UTTAR PRADESH",3353.915805,6.880540e+05,"POLYGON ((8835826.117 3111325.9917, 8835587.89..."
2,441999,KHUMAN PURA,09,146,00770,,UTTAR PRADESH,Agra,Bah,,...,,770,BAH,805,None,94,", Bah,Agra,UTTAR PRADESH",4186.293700,9.663986e+05,"POLYGON ((8734287.825 3107038.8388, 8734670.43..."
3,442064,BIRU NAGAR,09,146,00766,124650,UTTAR PRADESH,Agra,Agra,Brahmnagar,...,AKBARPUR,766,BARAULI AHIR,806,None,90,"Brahmnagar , Agra,Agra,UTTAR PRADESH",5294.335159,1.441254e+06,"POLYGON ((8693367.7743 3138457.6121, 8692999.5..."
4,442065,SARAI,09,146,00766,,UTTAR PRADESH,Agra,Agra,,...,,766,BICHPURI,807,None,87,", Agra,Agra,UTTAR PRADESH",5716.985670,1.981435e+06,"POLYGON ((8684825.0698 3139415.3034, 8684281.0..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101724,542787,KARAILA BAG,09,175,00890,943316,UTTAR PRADESH,Prayagraj,Allahabad,Kraila Bag,...,,890,KAURIHAR,839,None,253,"Kraila Bag , Allahabad,Prayagraj,UTTAR PRADESH",5403.368035,8.548021e+05,"POLYGON ((9106075.8825 2926266.2022, 9106445.4..."
101725,542788,SULEM SARAIN,09,175,00890,,UTTAR PRADESH,Prayagraj,Allahabad,,...,,890,KAURIHAR,839,None,253,", Allahabad,Prayagraj,UTTAR PRADESH",4669.327248,1.175959e+06,"POLYGON ((9103022.4304 2930865.4547, 9102496.4..."
101726,542789,BADSHAHIMANDI,09,175,00890,,UTTAR PRADESH,Prayagraj,Allahabad,,...,,890,KAURIHAR,839,None,263,", Allahabad,Prayagraj,UTTAR PRADESH",6099.315814,1.763043e+06,"POLYGON ((9113062.2242 2930346.2085, 9112982.8..."
101727,583847,R F,09,196,00994,208425,UTTAR PRADESH,Chandauli,Chakia,Sitadhar,...,DHANKUAWARI KALAN,994,SAHABGANJ,1040,None,383,"Sitadhar , Chakia,Chandauli,UTTAR PRADESH",55950.963661,4.139544e+07,"POLYGON ((9272481.9864 2878510.7137, 9272417.3..."
101728,583848,TULSIPUR RESERVED FOREST,09,182,00926,,UTTAR PRADESH,Balrampur,Tulsipur,,...,,926,PACHPEDWA,929,None,292,", Tulsipur,Balrampur,UTTAR PRADESH",132728.025492,1.330405e+08,"POLYGON ((9209511.9994 3205315.3322, 9208718.4..."

In [7]:
up_vil_unfiltered = up_vil_unfiltered
up_vil = up_vil_unfiltered.replace(r'^\s*$', np.nan, regex=True)
up_vil = up_vil.dropna(subset=['vilnam_soi'])
up_vil = up_vil.dropna(subset=['vilname11'])
vil_name= up_vil['vilname11'].to_list()
vil_name

['Kuchela',
 'Brahmnagar',
 'Kalika Nagla',
 'Songarha',
 'Nandapur',
 'Parbatpur',
 'Mihawa',
 'Kukandai',
 'Basai Bhadoriya',
 'Rahalai',
 'Mewali Khurd',
 'Gahara Khurd',
 'Rithai',
 'Nadim',
 'Patti Pachgain',
 'Dhamota',
 'Bamanpura',
 'Bailoth',
 'Vipraoli',
 'Charitha',
 'Soni Khera',
 'Nauni',
 'Garhi Ahir',
 'Nadau',
 'Poiya',
 'Akabara',
 'Ujrai',
 'Kasoti',
 'Naharra',
 'Thap Khargh',
 'Ladukhera',
 'Ratauti',
 'Mai Bujurg',
 'Sirauli',
 'Didhwar',
 'Biraharu',
 'Lahara',
 'Udhannapura',
 'Kookapur',
 'Jaitpura Kalan',
 'Gadoli Kalan',
 'Uncha',
 'Parana',
 'Ujhaoli',
 'Kolara Khurd',
 'Swara',
 'Gungawali',
 'Tantpur',
 'Burhera',
 'Patharkot',
 'Mangarol Gujar',
 'Nagariya',
 'Qutubpur Gola',
 'Bamnai Khurd',
 'Pairatia',
 'Mahapur',
 'Barhan',
 'Hanspura',
 'Raipuradixit',
 'Kondari',
 'Garhi Baroli',
 'Bisahara',
 'Kheria',
 'Kuthawati',
 'Hirner Newadakhera',
 'Seola Gaurwa',
 'Bhandai',
 'Islampur',
 'Arela',
 'Swami Mustkil',
 'Hasanpur',
 'Mitaoli',
 'Dhanaula Khurd',
 'Usmanpur',
 'Mahra Chaudhri',
 'Baiman',
 'Singaicha',
 'Salempur Ghankar',
 'Soun',
 'Babrod',
 'Bhagupur',
 'Kurgawan Khokar',
 'Bhopur Kheragarh',
 'Midkoli',
 'Vijoli',
 'Dahgawan',
 'Basai Kalan',
 'Thap Mahadwari',
 'Nauphari',
 'Mukhwar',
 'Ramnagar Khandauli',
 'Ruppur',
 'Tamanchgarh',
 'Mai',
 'Garhima',
 'Basaia Rajput',
 'Sikandar Pur',
 'Nagla Mawai',
 'Gauharpur',
 'Tiwaha',
 'Kalwari (CT)',
 'Samogar Ehtmali',
 'Garhsani',
 'Mahadau',
 'Garhi Chandraman',
 'Etmadpur Madra',
 'Mehra Naharganj',
 'Mansoorpura',
 'Siahipura',
 'Mundhera',
 'Sunhara',
 'Balhera',
 'Tajpur',
 'Basai Jagner',
 'Kharagpura',
 'Naugawan',
 'Pachmori',
 'Roodhau',
 'Richhoha',
 'Mankenda',
 'Ayela',
 'Taharpur',
 'Nagla Dhir',
 'Khaspur Mustkil',
 'Biloni',
 'Nichakhera',
 'Sankuri Kalan',
 'Gohra',
 'Uttoo',
 'Pachgain Khera',
 'Khal',
 'Jarua Katra',
 'Janara',
 'Sikargarhi',
 'Lalpur',
 'Bhara',
 'Jheetpura',
 'Mudiyapura',
 'Uganpura',
 'Sarai Ahmad',
 'Paprinagar',
 'Bhonigapura',
 'Mahdewa',
 'Jawaharpur',
 'Seola Ahir',
 'Kutabpur Gujar',
 'Baharabati Khas',
 'Gothara',
 'Hingot Kheria',
 'Dhanauli (CT)',
 'Bidyapur',
 'Bamrauli Katara',
 'Mayapura',
 'Lakavali',
 'Chamrauli',
 'Azizpur (CT)',
 'Kharagpur',
 'Nagla Beal',
 'Naubari',
 'Akhbai',
 'Badanpur Barnamai',
 'Bhilawali',
 'Dharmasala',
 'Devpura',
 'Shahapur Goojar',
 'Ardaya',
 'Rasulpur Sadar',
 'Tanora Nurpur Mustkil',
 'Gijauli Must',
 'Thana Shankar Dwari',
 'Raghupura',
 'Alampur',
 'Sadupura',
 'Kharbai',
 'Bhilawati',
 'Surehra (Must.)',
 'Mohammadpur',
 'Chainkora',
 'Malikpur',
 'Nahchani',
 'Sutendi',
 'Khera Bakanda',
 'Khicharpura',
 'Changoli',
 'Tilupura',
 'Roopdhandu',
 'Aharan',
 'Siroli',
 'Sikari 2 Hissa',
 'Rasulpur Kiraoli',
 'Sagunapur',
 'Bisarna',
 'Agwarkhas',
 'Nimena',
 'Bihari',
 'Isauli',
 'Patti Shaikhupur',
 'Bishrampur',
 'Doora',
 'Bamrauli',
 'Karanpura',
 'Gadhia Pratappura',
 'Kwaari',
 'Panota',
 'Rasulpur',
 'Cheetpur',
 'Lahchora',
 'Nawalpur',
 'Mubarizpur',
 'Bhenson',
 'Patparganj',
 'Ondh',
 'Gamari',
 'Fatehpur Sikri (NPP)',
 'Ujarai',
 'Panchakki',
 'Akbarpur',
 'Abhaudopura',
 'Nazirpura',
 'Pawawali',
 'Murlidharpur',
 'Baripura',
 'Bharhkol',
 'Mukutpura',
 'Amahi',
 'Karanpuri',
 'Singrawali',
 'Mahua',
 'Rampuragdhi',
 'Nasaua',
 'Manghatai',
 'Sahata',
 'Sadarban',
 'Budhana Mustkil',
 'Karmana Mustkil',
 'Shyamo',
 'Nagla Mangoli',
 'Gadhi Shripati',
 'Paliya',
 'Biruni',
 'Nagla Mani',
 'Gangaura',
 'Barobara Khurd',
 'Fatehpura',
 'Neemdanda',
 'Nagla Sarup',
 'Nagla Duleh Khan',
 'Chirhauli',
 'Nagla Sirji',
 'Sorai',
 'Benai',
 'Bamnai Kalan',
 'Seha',
 'Jain Gara',
 'Sujgai',
 'Siktara',
 'Bichola',
 'Sikrara',
 'Nagla Mohare',
 'Vijkoli',
 'Mangoli Khurd',
 'Babarpur',
 'Dhimsiri',
 'Bilahani',
 'Karhaki',
 'Ghaskata',
 'Kunwar Kheda',
 'Krapal Pura',
 'Khandauli (CT)',
 'Bhahai',
 'Gajoura',
 'Bho Pur',
 'Baseri Chahar',
 'Gujarpura',
 'Shahidpur',
 'Dadukara',
 'Santha',
 'Chauma Shahpur',
 'Sarvatpur',
 'Chamraua',
 'Mau',
 'Singna',
 'Kitham',
 'Sehta',
 'Undera',
 'Nagla Nathu',
 'Mutnai',
 'Jautana',
 'Deori',
 'Kheri Aru',
 'Barauli Ahir',
 'Nagla Mahasingh',
 'Sihorgarh',
 'Achhnera (NPP)',
 'Bhogpur',
 'Lakhanpura',
 'Kankar Kheda',
 'Basai Kheragarh',
 'Bichpuri',
 'Manona',
 'Singaicha',
 'Jharothi',
 'Gurha',
 'Gutla',
 'Indon',
 'Mohammadpur',
 'Pali Kiraoli',
 'Saimari',
 'Mori',
 'Khera Jat',
 'Nagar Chand',
 'Pinani Ramnagar',
 'Uncha',
 'Murawal',
 'Bishara Kalan',
 'Chuharpur',
 'Baman',
 'Chaukra',
 'Bandhanu',
 'Kharkana',
 'Kolara Kalan',
 'Lalau',
 'Mandoli',
 'Mewali Kalan',
 'Jajau',
 'Nurpur',
 'Basaiya Bobla',
 'Lodhai',
 'Malpura',
 'Anguthi',
 'Nayepura',
 'Baghour',
 'Lakhanpur Khalsa',
 'Pundrikpura',
 'Sujanpura',
 'Renka',
 'Lakhanpura Jogir',
 'Shekhupur',
 'Maraina',
 'Jaganpur',
 'Padkoli',
 'Chhattapura',
 'Kot',
 'Biharipur',
 'Dharera',
 'Hansela',
 'Arsena',
 'Chaugan',
 'Milik',
 'Gadhbar',
 'Nagriya',
 'Talab Buriya',
 'Chha Pokhar',
 'Murthar Alipur',
 'Simrahi',
 'Shahganj',
 'Gonsili',
 'Tarauli Gujar',
 'Nagla Kasimpur',
 'Sunsar',
 'Sitouli',
 'Kalinjar',
 'Arhera',
 'Garhi Udairaj',
 'Chandrapur',
 'Maharajpur',
 'Digrauta',
 'Kanharpura',
 'Kiraoali (NP)',
 'Abhaypura',
 'Nanau',
 'Kulhara',
 'Kamtari',
 'Kukawar',
 'Musepura',
 'Koomppura',
 'Sarangpur',
 'Tehra',
 'Hasnabad',
 'Khanda',
 'Tarhat',
 'Hasan Jahanpur',
 'Jamalnagar Bhains',
 'Babarpur Ehtmali',
 'Mai',
 'Hironda',
 'Pusenta',
 'Basai Goojar',
 'Bhari Nagla',
 'Manikpura',
 'Baghrena',
 'Bhawanpura',
 'Devri',
 'Badous',
 'Utsana',
 'Mitaili',
 'Mangalpur Bartara',
 'Silokhar',
 'Bhitari',
 'Kherdanda',
 'Surajpura',
 'Penti Khera',
 'Bakalpur',
 'Raipura Ahir',
 'Rohai Khas',
 'Budhera',
 'Shahved',
 'Ata',
 'Pidhora',
 'Basai Khurd',
 'Patholi (CT)',
 'Laramada',
 'Deoretha (CT)',
 'Mahua Khera',
 'Sannpura',
 'Maloni',
 'Phulpur',
 'Kagarol',
 'Mangoli Kalan',
 'Hingot Khera',
 'Luhari Fatehabad',
 'Gurha',
 'Kahrai',
 'Abhaypura',
 'Davli',
 'Bijhamai',
 'Dodapura',
 'Dhobai',
 'Manhgoli',
 'Loheta',
 'Badagaon',
 'Emanpura',
 'Kachhpura',
 'Narholi',
 'Mangadpur',
 'Pharaiyapura',
 'Chousingi',
 'Barenda',
 'Gorau',
 'Madan Pur Must',
 'Khilawali',
 'Paharpura',
 'Banpur',
 'Bhalokhara',
 'Tondra',
 'Indraini',
 'Lahar Patti',
 'Gadpura',
 'Dehtora (CT)',
 'Kukathala',
 'Runkata (CT)',
 'Runkata (CT)',
 'Mubarikpur',
 'Bharapur',
 'Naraul',
 'Bamrauli Ahir',
 'Tas Pura',
 'Karaudhna',
 'Teekri',
 'Jampur',
 'Maharampur',
 'Tehra Rawat',
 'Jajauli',
 'Rithaura',
 'Nagla Lohiya',
 'Jagraj Pura',
 'Ran Pura',
 'Dhaurra',
 'Babarpur Mustkil',
 'Murenda',
 'Artauni (CT)',
 'Bastai',
 'Bahrampur',
 'Barna',
 'Sankuri Khurd',
 'Sekhpur Nagla',
 'Shahpur Rakauli',
 'Fatehabad (NP)',
 'Khera Jawahar',
 'Sakatpur',
 'Sucheta',
 'Rajaura',
 'Midhakur',
 'Khanpur Nithari',
 'Dhanoli',
 'Samogar Mustkil',
 'Pyarampura',
 'Barauli Gujar',
 'Garhi Karimpur',
 'Shamsabad (NPP)',
 'Nagla Patam',
 'Chandi',
 'Kurra Chitterpur',
 'Salempur Muria',
 'Salahnagar Barbar',
 'Pharairi',
 'Murkia',
 'Dulhara',
 'Kundol',
 'Patsal',
 'Mohanpur',
 'Sherpur',
 'Qutubpur Rohai',
 'Pharaira',
 'Bargawan Buzurg',
 'Sherkhan',
 'Nagla Kuwar Janubi',
 'Anwal Khera',
 'Seora',
 'Pesai',
 'Jatpura',
 'Banguri',
 'Sunana',
 'Rojauli',
 'Basaia Raimol',
 'Salemabad',
 'Akola',
 'Nagla Bhikki',
 'Jonai',
 'Bitholi',
 'Vrishangpura',
 'Brithala',
 'Sidhavli',
 'Chamrauli',
 'Begampur',
 'Jitora',
 'Ikthara',
 'Khedia',
 'Nagla Dalel',
 'Mevli',
 'Sutahari',
 'Holy Pura',
 'Bhikanpur',
 'Bidholi Kheragarh',
 'Bilpura',
 'Nibohra',
 'Arjun Pura',
 'Mevla',
 'Chachond',
 'Chorangabehar',
 'Raipura Bhadoriya',
 'Fatehpura',
 'Kuberpur',
 'Mangura',
 'Anganpura',
 'Jugsena',
 'Nekpur',
 'Beerai',
 'Tor',
 'Jahanpur',
 'Pratappura',
 'Pauser',
 'Daudpur',
 'Pathakpura',
 'Kachora Ghat',
 'Shahapur Brahaman',
 'Madhepura',
 'Jarar',
 'Rajpura',
 'Balai',
 'Ghoroli',
 'Agarpur',
 'Untgiri',
 'Basai Arela',
 'Shahpur Khalsa',
 'Korai',
 'Rajrai',
 'Sikandarpur Mustkil',
 'Garhi Pirthi',
 'Rasulpur',
 'Dhanina',
 'Bishari Bhand',
 'Bain Khera',
 'Baseri Sikander',
 'Swain',
 'Richhapura',
 'Udaypur Kalan',
 'Jojalipura',
 'Khetlipura',
 'Zebara',
 'Derak',
 'Rooppura',
 'Dhaypura',
 'Khajuhapura',
 'Samaramau',
 'Kachora',
 'Pai',
 'Jalalpur',
 'Kanaharpura',
 'Basoni',
 'Dagroopura',
 'Umretha',
 'Malupur',
 'Chourangahar',
 'Nayagaon',
 'Nahtoli',
 'Rithori',
 'Ramgarh',
 'Etmadpur Ajnera',
 'Cheet',
 'Garhibachchi',
 'Nonera',
 'Khandar',
 'Rihauli',
 'Rampur',
 'Nagla Tulsi',
 'Dhangrauli Must',
 'Gurha',
 'Mangarol Gujar',
 'Bhopur Jagner',
 'Jagner (NP)',
 'Shahpur Jagner',
 'Kentholi',
 'Motipura',
 'Mukhrai',
 'Nagla Veerbhan',
 'Vikarampur',
 'Husainpura',
 'Ladhavapura',
 'Dankasa',
 'Kathumari',
 'Gulabganj',
 'Sajaiti',
 'Tarason',
 'Purakanera',
 'Siktra',
 'Rajpura',
 'Udaypur Khalsa',
 'Veri',
 'Bidhouli Jagner',
 'Bazidpur',
 'Bhaupura',
 'Thansera',
 'Kukthari',
 'Kaliyanpura',
 'Deenpura',
 'Bah (NPP)',
 'Bargawan Khurd',
 'Lalpura',
 'Lakhurani',
 'Karahi',
 'Tapara',
 'Mahabatpur',
 'Barauli',
 'Imlabada',
 'Bhadroli',
 'Gugawand',
 'Chandsora',
 'Gopal Pura',
 'Nagoo Pura',
 'Rudmuli',
 'Udena',
 'Darki',
 'Mai',
 'Garsan',
 'Mahua Khera',
 'Jajau',
 'Rampur Chandrasaini',
 'Etmadpur Madra',
 'Bateshwar',
 'Syaich',
 'Usarra',
 'Himayunpur Rohai',
 'Khanpur',
 'Rasulpur',
 'Mahao',
 'Saiyan',
 'Arnota',
 'Serab',
 'Bhadaura',
 'Siarmau',
 'Sarendhi',
 'Nagar',
 'Ghusiana',
 'Gubrari',
 'Dhanaula Kalan',
 'Danda',
 'Shahpur Toola',
 'Bhaker',
 'Pipretha',
 'Lohari Iradatnagar',
 'Rampura',
 'Bhanpura',
 'Basai',
 'Muzaffarpur',
 'Sarenda',
 'Sankuri Khurd',
 'Nagla Shadhi',
 'Bhojpur',
 'Bakalpur',
 'Barobara Kalan',
 'Jarari',
 'Jarauli',
 'Dabari',
 'Mithpura',
 'Ghaghpura',
 'Arrji Paliya',
 'Gubrauth',
 'Pratap Pura',
 'Garhi Dariyab',
 'Sudhrai',
 'Humayonpur Gujar',
 'Gidron',
 'Deorentha',
 'Usara',
 'Jalalpur',
 'Bidrai',
 'Khera Bhagor',
 'Baha',
 'Beesalpur',
 'Mahra Chaudhri',
 'Salemabad',
 'Sarsa',
 'Sonothi',
 'Gangraua',
 'Sika Rauda',
 'Kalayan Pur',
 'Chitaura',
 'Beri Chahar',
 'Dabar',
 'Amanabad',
 'Chamraula',
 'Tehu',
 'Sujanpur',
 'Bedpura',
 'Khallauwa',
 'Therai',
 'Deonari',
 'Kolari',
 'Aulenda',
 'Ikram Nagar',
 'Nagla Haji',
 'Gahara Kalan',
 'Bad',
 'Nagla Sarai',
 'Wazidpur',
 'Kaboolpur',
 'Mandi Mirza Khan',
 'Aie',
 'Bisauri Gaurwa',
 'Nanpur',
 'Kakrari',
 'Behri',
 'Digner',
 'Dauki',
 'Bajhera',
 'Kakua',
 'Lakhanpur',
 'Thapenra',
 'Kheragarh (NP)',
 'Noharika',
 'Shahpur Nadim',
 'Pai Ghusiyan',
 'Sonra',
 'Itaura',
 'Gur Ki Mandi',
 'Jakhoda',
 'Samara',
 'Nagla Sikarwar',
 'Karahara',
 'Rohta (CT)',
 'Paroli Sikarwar',
 'Sahanpur',
 'Nainana Jat (CT)',
 'Budhera',
 'Nadauta',
 'Karahi',
 'Kaulakha (CT)',
 'Singarpur',
 'Janutha',
 'Agwarkhas',
 'Khera Sadhan',
 'Nayabans',
 'Samogar Mustkil',
 'Sandhan',
 'Pant Khara',
 'Nagla Pachauri',
 'Turkia',
 'Nagla Arrua',
 'Raibha',
 'Tirpuri',
 'Nagar',
 'Sunari',
 'Atus',
 'Churiyari',
 'Kalal Kheria',
 'Barara',
 'Ninbaya',
 'Baroda Sadar',
 'Parihar',
 'Mahuar',
 'Tora',
 'Sahara',
 'Daultabad',
 'Baseri Kazi',
 'Kuan Khera',
 'Basua Nagla',
 'Puramana',
 'Sargan Khera',
 'Gopau',
 'Naya Bass',
 'Pali Sadar',
 'Thapi',
 'Samogar Ehtmali',
 'Sahai',
 'Biyara',
 'Chauhatna',
 'Semra',
 'Jamnipur',
 'Jaupura',
 'Mangarol Jat',
 'Gobra',
 'Raipur',
 'Arrua Khas',
 'Kheriya Khandauli',
 'Kathawari',
 'Rahankalan',
 'Dhaurra',
 'Bhandiri',
 'Lakhanpur',
 'Rahan Khurd',
 'Panwari',
 'Mohammadpur',
 'Loh Karera',
 'Kachaura',
 'Baipur Ehtmali',
 'Artauni (CT)',
 'Lakhna Mai',
 'Sarai Day Ruppa',
 'Khera Rathor',
 'Gonsili',
 'Mundi Jahangirpur',
 'Khandia',
 'Mutawai',
 'Bajidpura',
 'Chauma Farah',
 'Siktara',
 'Kookapur',
 'Zebara',
 'Dagroopura',
 'Nagla Udiya',
 'Dharmasala',
 'Simrahi',
 'Maloni',
 'Raipura',
 'Chitrahar',
 'Chitrahar',
 'Chitrahar',
 'Chitrahar',
 'Nagla Kuwar Janubi',
 'Garhi Pirthi',
 'Shahapur Goojar',
 'Maloni',
 'Hazipur Khera',
 'Nagla Kuwar Shumali',
 'Mohisinabad',
 'Saifuddinpur',
 'Bhartar',
 'Bichoula',
 'Kachora Ghat',
 'Kamoni',
 'Korath',
 'Kenjra',
 'Jajau',
 'Khohara',
 'Goharra',
 'Pahari Kalan',
 'Naugawan',
 'Nagla Bhikki',
 'Jaitpur Khurd',
 'Keelpura',
 'Naugawan',
 'Bagda',
 'Surothi',
 'Swamibagh (NP)',
 'Aurangpur',
 'Bainpur Mustkil',
 'Khairaini',
 'Chitrahar',
 'Serab',
 'Bhidawali',
 'Kookapur',
 'Kookapur',
 'Kunwar Kheda',
 'Tasond',
 'Etmadpur (NPP)',
 'Maloni',
 'Maloni',
 'Khera Rathor',
 'Nasaua',
 'Khohri',
 'Agra (CB)',
 'Bamroli',
 'Nadgawan',
 'Shahapur Goojar',
 'Itaili',
 'Pinahat (NP)',
 'Dharmasala',
 'Talab Buriya',
 'Rohai Khas',
 'Nagla Kisana',
 'Pai',
 'Khera Rathor',
 'Maloni',
 'Khicharpura',
 'Dadupura',
 'Chandrapura',
 'Maloni',
 'Maloni',
 'Bah',
 'Bijauna Khurd',
 'Shahapur Goojar',
 'Khilawali',
 'Kunwar Kheda',
 'Bamroli',
 'Bichoula',
 'Bichoula',
 'Basoni',
 'Kiyori',
 'Chitrahar',
 'Kiyori',
 'Kherdanda',
 'Sankuri Khurd',
 'Pahari Khurd',
 'Chhitapur Nagla Birai',
 'Jarari',
 'Nagla Inami',
 'Gadoli Khurd',
 'Surehra (Must.)',
 'Swami Mustkil',
 'Himayunpur Edoin',
 'Abhaidopura',
 'Supahara',
 'Chaoli',
 'Nera Khadar',
 'Nawali',
 'Bithona',
 'Kharik',
 'Karkoli',
 'Mahua',
 'Simrahi',
 'Barenda',
 'Hatkant',
 'Chikanipura',
 'Korath',
 'Dabhaura',
 'Reha',
 'Utsana',
 'Zebara',
 'Kenjra',
 'Kharik',
 'Kyari',
 'Zebara',
 'Basoni',
 'Manhgoli',
 'Karkoli',
 'Kenjra',
 'Ranipura',
 'Kiyori',
 'Nadgawan',
 'Kamoni',
 'Purabhagwan',
 'Reha',
 'Baghrena',
 'Bithona',
 'Mau',
 'Kyari',
 'Gurha',
 'Chikanipura',
 'Mahua',
 'Pinaht',
 'Vipraoli',
 'Veerpur Chhabil Garhi',
 'Bamroli',
 'Khera Rathor',
 'Kamoni',
 'Gonsili',
 'Dharmasala',
 'Umretha',
 'Bamroli',
 'Elampura',
 'Talepur',
 'Rasulpur',
 'Bhagatpur',
 'Bhagwanpur',
 'Kaliyanpur',
 'Tajpur',
 'Jadaupur',
 'Usmanpur',
 'Peepali',
 'Baijla',
 'Jamuna',
 'Kirthala',
 'Daheli',
 'Syaraul',
 'Pahar Garhi',
 'Baimbirpur',
 'Araji Jangal',
 'Barauli',
 'Sabalpur',
 ...]

In [8]:
up_vil = up_vil.loc[~up_vil['vilcode11'].isna()]
up_vil

,objectid,vilnam_soi,stcode11,dtcode11,sdtcode11,vilcode11,stname,dtname,sdtname,vilname11,...,gp_name,subdt_lgd,block_name,block_lgd,remark,ac_no,search_village,st_length(shape),st_area(shape),geometry
1,447787,KUCHELA,09,162,00841,148028,UTTAR PRADESH,Auraiya,Bidhuna,Kuchela,...,KUKARKAT,841,ERWA KATRA,864,None,202,"Kuchela , Bidhuna,Auraiya,UTTAR PRADESH",3353.915805,6.880540e+05,"POLYGON ((8835826.117 3111325.9917, 8835587.89..."
3,442064,BIRU NAGAR,09,146,00766,124650,UTTAR PRADESH,Agra,Agra,Brahmnagar,...,AKBARPUR,766,BARAULI AHIR,806,None,90,"Brahmnagar , Agra,Agra,UTTAR PRADESH",5294.335159,1.441254e+06,"POLYGON ((8693367.7743 3138457.6121, 8692999.5..."
5,442066,MALINAGLA,09,146,00766,124637,UTTAR PRADESH,Agra,Agra,Kalika Nagla,...,KALIKA NAGLA,766,BARAULI AHIR,806,None,90,"Kalika Nagla , Agra,Agra,UTTAR PRADESH",4437.474219,1.165989e+06,"POLYGON ((8687579.8113 3139642.746, 8686879.81..."
7,445126,SONGARHA,09,706,00914,169561,UTTAR PRADESH,Amethi,Amethi,Songarha,...,AGRESAR,914,BHADAR,1581,None,186,"Songarha , Amethi,Amethi,UTTAR PRADESH",2347.873458,3.660032e+05,"POLYGON ((9131294.888 3012187.6331, 9130987.70..."
11,441464,PARBATPUR,09,146,00765,124463,UTTAR PRADESH,Agra,Etmadpur,Parbatpur,...,HAZIPUR,765,KHANDAULI,813,None,86,"Parbatpur , Etmadpur,Agra,UTTAR PRADESH",4836.618980,1.082456e+06,"POLYGON ((8682774.4653 3163422.9401, 8682560.9..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101713,542776,TARAPUR (BHOPATPUR),09,175,00890,160724,UTTAR PRADESH,Prayagraj,Allahabad,Bhoopatpur Uparhar,...,BHOPATPUR,890,BHAGWATPUR,7359,None,253,"Bhoopatpur Uparhar , Allahabad,Prayagraj,UTTAR...",5225.435382,1.729794e+06,"POLYGON ((9107327.329 2918701.8091, 9105978.58..."
101719,542782,MAKHANPUR,09,175,00890,160719,UTTAR PRADESH,Prayagraj,Allahabad,Makhdoompur Khas,...,MAQDOOM PUR,890,BHAGWATPUR,7359,None,253,"Makhdoompur Khas , Allahabad,Prayagraj,UTTAR P...",7823.424764,3.499521e+06,"POLYGON ((9096536.5803 2924031.6525, 9096288.3..."
101723,542786,RAJAPUR DEHMAHI,09,175,00890,943340,UTTAR PRADESH,Prayagraj,Allahabad,Rajapur Deh Maafi,...,NaN,890,KAURIHAR,839,None,261,"Rajapur Deh Maafi , Allahabad,Prayagraj,UTTAR ...",5158.007395,1.289218e+06,"POLYGON ((9107223.341 2934658.6766, 9107223.05..."
101724,542787,KARAILA BAG,09,175,00890,943316,UTTAR PRADESH,Prayagraj,Allahabad,Kraila Bag,...,NaN,890,KAURIHAR,839,None,253,"Kraila Bag , Allahabad,Prayagraj,UTTAR PRADESH",5403.368035,8.548021e+05,"POLYGON ((9106075.8825 2926266.2022, 9106445.4..."
101727,583847,R F,09,196,00994,208425,UTTAR PRADESH,Chandauli,Chakia,Sitadhar,...,DHANKUAWARI KALAN,994,SAHABGANJ,1040,None,383,"Sitadhar , Chakia,Chandauli,UTTAR PRADESH",55950.963661,4.139544e+07,"POLYGON ((9272481.9864 2878510.7137, 9272417.3..."

In [9]:
up_vil = up_vil.loc[up_vil["stname"] == "UTTAR PRADESH"]
up_vil["vilnam_soi"] = up_vil["vilnam_soi"].str.upper()
up_vil = up_vil[~up_vil["vilnam_soi"].str.contains("FOREST", na=False)]
up_vil = up_vil[~up_vil["vilnam_soi"].str.contains("RF", na=False)]
up_vil = up_vil[~up_vil["vilnam_soi"].str.contains("RESERVED FOREST", na=False)]
#up_vil = up_vil[~up_vil["vilnam_soi"].str.contains("D.P.F", na=False)]
up_vil = up_vil[~up_vil["vilnam_soi"].str.contains(" RF", na=False)]
up_vil = up_vil[~up_vil["vilnam_soi"].str.contains("HILL", na=False)]
up_vil = up_vil[~up_vil["vilnam_soi"].str.contains("R F", na=False)]
up_vil

,objectid,vilnam_soi,stcode11,dtcode11,sdtcode11,vilcode11,stname,dtname,sdtname,vilname11,...,gp_name,subdt_lgd,block_name,block_lgd,remark,ac_no,search_village,st_length(shape),st_area(shape),geometry
1,447787,KUCHELA,09,162,00841,148028,UTTAR PRADESH,Auraiya,Bidhuna,Kuchela,...,KUKARKAT,841,ERWA KATRA,864,None,202,"Kuchela , Bidhuna,Auraiya,UTTAR PRADESH",3353.915805,6.880540e+05,"POLYGON ((8835826.117 3111325.9917, 8835587.89..."
3,442064,BIRU NAGAR,09,146,00766,124650,UTTAR PRADESH,Agra,Agra,Brahmnagar,...,AKBARPUR,766,BARAULI AHIR,806,None,90,"Brahmnagar , Agra,Agra,UTTAR PRADESH",5294.335159,1.441254e+06,"POLYGON ((8693367.7743 3138457.6121, 8692999.5..."
5,442066,MALINAGLA,09,146,00766,124637,UTTAR PRADESH,Agra,Agra,Kalika Nagla,...,KALIKA NAGLA,766,BARAULI AHIR,806,None,90,"Kalika Nagla , Agra,Agra,UTTAR PRADESH",4437.474219,1.165989e+06,"POLYGON ((8687579.8113 3139642.746, 8686879.81..."
7,445126,SONGARHA,09,706,00914,169561,UTTAR PRADESH,Amethi,Amethi,Songarha,...,AGRESAR,914,BHADAR,1581,None,186,"Songarha , Amethi,Amethi,UTTAR PRADESH",2347.873458,3.660032e+05,"POLYGON ((9131294.888 3012187.6331, 9130987.70..."
11,441464,PARBATPUR,09,146,00765,124463,UTTAR PRADESH,Agra,Etmadpur,Parbatpur,...,HAZIPUR,765,KHANDAULI,813,None,86,"Parbatpur , Etmadpur,Agra,UTTAR PRADESH",4836.618980,1.082456e+06,"POLYGON ((8682774.4653 3163422.9401, 8682560.9..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101709,542772,TIKARI,09,175,00890,161745,UTTAR PRADESH,Prayagraj,Allahabad,Tikri Kachhar,...,TIKARI UPERHAR,890,BHAGWATPUR,7359,None,253,"Tikri Kachhar , Allahabad,Prayagraj,UTTAR PRADESH",7326.333876,2.263367e+06,"POLYGON ((9095918.7895 2937263.123, 9095362.13..."
101713,542776,TARAPUR (BHOPATPUR),09,175,00890,160724,UTTAR PRADESH,Prayagraj,Allahabad,Bhoopatpur Uparhar,...,BHOPATPUR,890,BHAGWATPUR,7359,None,253,"Bhoopatpur Uparhar , Allahabad,Prayagraj,UTTAR...",5225.435382,1.729794e+06,"POLYGON ((9107327.329 2918701.8091, 9105978.58..."
101719,542782,MAKHANPUR,09,175,00890,160719,UTTAR PRADESH,Prayagraj,Allahabad,Makhdoompur Khas,...,MAQDOOM PUR,890,BHAGWATPUR,7359,None,253,"Makhdoompur Khas , Allahabad,Prayagraj,UTTAR P...",7823.424764,3.499521e+06,"POLYGON ((9096536.5803 2924031.6525, 9096288.3..."
101723,542786,RAJAPUR DEHMAHI,09,175,00890,943340,UTTAR PRADESH,Prayagraj,Allahabad,Rajapur Deh Maafi,...,NaN,890,KAURIHAR,839,None,261,"Rajapur Deh Maafi , Allahabad,Prayagraj,UTTAR ...",5158.007395,1.289218e+06,"POLYGON ((9107223.341 2934658.6766, 9107223.05..."
101724,542787,KARAILA BAG,09,175,00890,943316,UTTAR PRADESH,Prayagraj,Allahabad,Kraila Bag,...,NaN,890,KAURIHAR,839,None,253,"Kraila Bag , Allahabad,Prayagraj,UTTAR PRADESH",5403.368035,8.548021e+05,"POLYGON ((9106075.8825 2926266.2022, 9106445.4..."

In [11]:
up_vil['dtcode11'] = up_vil['dtcode11'].astype(str).apply(lambda x: x.zfill(2))
up_vil['block_lgd'] = up_vil['block_lgd'].astype(float).astype(int).astype(str).apply(lambda x: x.zfill(5))
up_vil['object_id'] = up_vil.apply(lambda row: f"21-{row['dtcode11']}-{row['block_lgd']}", axis=1)
up_vil

,objectid,vilnam_soi,stcode11,dtcode11,sdtcode11,vilcode11,stname,dtname,sdtname,vilname11,...,subdt_lgd,block_name,block_lgd,remark,ac_no,search_village,st_length(shape),st_area(shape),geometry,object_id
1,447787,KUCHELA,09,162,00841,148028,UTTAR PRADESH,Auraiya,Bidhuna,Kuchela,...,841,ERWA KATRA,00864,None,202,"Kuchela , Bidhuna,Auraiya,UTTAR PRADESH",3353.915805,6.880540e+05,"POLYGON ((8835826.117 3111325.9917, 8835587.89...",21-162-00864
3,442064,BIRU NAGAR,09,146,00766,124650,UTTAR PRADESH,Agra,Agra,Brahmnagar,...,766,BARAULI AHIR,00806,None,90,"Brahmnagar , Agra,Agra,UTTAR PRADESH",5294.335159,1.441254e+06,"POLYGON ((8693367.7743 3138457.6121, 8692999.5...",21-146-00806
5,442066,MALINAGLA,09,146,00766,124637,UTTAR PRADESH,Agra,Agra,Kalika Nagla,...,766,BARAULI AHIR,00806,None,90,"Kalika Nagla , Agra,Agra,UTTAR PRADESH",4437.474219,1.165989e+06,"POLYGON ((8687579.8113 3139642.746, 8686879.81...",21-146-00806
7,445126,SONGARHA,09,706,00914,169561,UTTAR PRADESH,Amethi,Amethi,Songarha,...,914,BHADAR,01581,None,186,"Songarha , Amethi,Amethi,UTTAR PRADESH",2347.873458,3.660032e+05,"POLYGON ((9131294.888 3012187.6331, 9130987.70...",21-706-01581
11,441464,PARBATPUR,09,146,00765,124463,UTTAR PRADESH,Agra,Etmadpur,Parbatpur,...,765,KHANDAULI,00813,None,86,"Parbatpur , Etmadpur,Agra,UTTAR PRADESH",4836.618980,1.082456e+06,"POLYGON ((8682774.4653 3163422.9401, 8682560.9...",21-146-00813
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101709,542772,TIKARI,09,175,00890,161745,UTTAR PRADESH,Prayagraj,Allahabad,Tikri Kachhar,...,890,BHAGWATPUR,07359,None,253,"Tikri Kachhar , Allahabad,Prayagraj,UTTAR PRADESH",7326.333876,2.263367e+06,"POLYGON ((9095918.7895 2937263.123, 9095362.13...",21-175-07359
101713,542776,TARAPUR (BHOPATPUR),09,175,00890,160724,UTTAR PRADESH,Prayagraj,Allahabad,Bhoopatpur Uparhar,...,890,BHAGWATPUR,07359,None,253,"Bhoopatpur Uparhar , Allahabad,Prayagraj,UTTAR...",5225.435382,1.729794e+06,"POLYGON ((9107327.329 2918701.8091, 9105978.58...",21-175-07359
101719,542782,MAKHANPUR,09,175,00890,160719,UTTAR PRADESH,Prayagraj,Allahabad,Makhdoompur Khas,...,890,BHAGWATPUR,07359,None,253,"Makhdoompur Khas , Allahabad,Prayagraj,UTTAR P...",7823.424764,3.499521e+06,"POLYGON ((9096536.5803 2924031.6525, 9096288.3...",21-175-07359
101723,542786,RAJAPUR DEHMAHI,09,175,00890,943340,UTTAR PRADESH,Prayagraj,Allahabad,Rajapur Deh Maafi,...,890,KAURIHAR,00839,None,261,"Rajapur Deh Maafi , Allahabad,Prayagraj,UTTAR ...",5158.007395,1.289218e+06,"POLYGON ((9107223.341 2934658.6766, 9107223.05...",21-175-00839
101724,542787,KARAILA BAG,09,175,00890,943316,UTTAR PRADESH,Prayagraj,Allahabad,Kraila Bag,...,890,KAURIHAR,00839,None,253,"Kraila Bag , Allahabad,Prayagraj,UTTAR PRADESH",5403.368035,8.548021e+05,"POLYGON ((9106075.8825 2926266.2022, 9106445.4...",21-175-00839

In [12]:
up_vil.columns

Index(['objectid', 'vilnam_soi', 'stcode11', 'dtcode11', 'sdtcode11',
       'vilcode11', 'stname', 'dtname', 'sdtname', 'vilname11', 'vil_lgd',
       'dist_lgd', 'state_lgd', 'gp_code', 'gp_name', 'subdt_lgd',
       'block_name', 'block_lgd', 'remark', 'ac_no', 'search_village',
       'st_length(shape)', 'st_area(shape)', 'geometry', 'object_id'],
      dtype='object')

In [13]:
up_vil = up_vil.drop(['object_id','remark', 'ac_no'],axis=1)
up_vil.to_file("/Users/stephensmathew/cdl_rep/flood-data-ecosystem-UP/Maps/up_ids-drr_shapefiles/UP_Villages_Boundary_Simplified.geojson")

### Urban shapes

In [14]:
up_urban = gpd.read_file("/Users/stephensmathew/cdl_rep/flood-data-ecosystem-UP/Maps/up_ids-drr_shapefiles/UP_Villages_Boundary_Simplified.geojson")
up_urban

,objectid,vilnam_soi,stcode11,dtcode11,sdtcode11,vilcode11,stname,dtname,sdtname,vilname11,...,state_lgd,gp_code,gp_name,subdt_lgd,block_name,block_lgd,search_village,st_length(shape),st_area(shape),geometry
0,447787,KUCHELA,09,162,00841,148028,UTTAR PRADESH,Auraiya,Bidhuna,Kuchela,...,9,46778,KUKARKAT,841,ERWA KATRA,00864,"Kuchela , Bidhuna,Auraiya,UTTAR PRADESH",3353.915805,6.880540e+05,"POLYGON ((8835826.117 3111325.9917, 8835587.89..."
1,442064,BIRU NAGAR,09,146,00766,124650,UTTAR PRADESH,Agra,Agra,Brahmnagar,...,9,42852,AKBARPUR,766,BARAULI AHIR,00806,"Brahmnagar , Agra,Agra,UTTAR PRADESH",5294.335159,1.441254e+06,"POLYGON ((8693367.7743 3138457.6121, 8692999.5..."
2,442066,MALINAGLA,09,146,00766,124637,UTTAR PRADESH,Agra,Agra,Kalika Nagla,...,9,42882,KALIKA NAGLA,766,BARAULI AHIR,00806,"Kalika Nagla , Agra,Agra,UTTAR PRADESH",4437.474219,1.165989e+06,"POLYGON ((8687579.8113 3139642.746, 8686879.81..."
3,445126,SONGARHA,09,706,00914,169561,UTTAR PRADESH,Amethi,Amethi,Songarha,...,9,90974,AGRESAR,914,BHADAR,01581,"Songarha , Amethi,Amethi,UTTAR PRADESH",2347.873458,3.660032e+05,"POLYGON ((9131294.888 3012187.6331, 9130987.70..."
4,441464,PARBATPUR,09,146,00765,124463,UTTAR PRADESH,Agra,Etmadpur,Parbatpur,...,9,43162,HAZIPUR,765,KHANDAULI,00813,"Parbatpur , Etmadpur,Agra,UTTAR PRADESH",4836.618980,1.082456e+06,"POLYGON ((8682774.4653 3163422.9401, 8682560.9..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95774,542772,TIKARI,09,175,00890,161745,UTTAR PRADESH,Prayagraj,Allahabad,Tikri Kachhar,...,9,44927,TIKARI UPERHAR,890,BHAGWATPUR,07359,"Tikri Kachhar , Allahabad,Prayagraj,UTTAR PRADESH",7326.333876,2.263367e+06,"POLYGON ((9095918.7895 2937263.123, 9095362.13..."
95775,542776,TARAPUR (BHOPATPUR),09,175,00890,160724,UTTAR PRADESH,Prayagraj,Allahabad,Bhoopatpur Uparhar,...,9,72881,BHOPATPUR,890,BHAGWATPUR,07359,"Bhoopatpur Uparhar , Allahabad,Prayagraj,UTTAR...",5225.435382,1.729794e+06,"POLYGON ((9107327.329 2918701.8091, 9105978.58..."
95776,542782,MAKHANPUR,09,175,00890,160719,UTTAR PRADESH,Prayagraj,Allahabad,Makhdoompur Khas,...,9,72912,MAQDOOM PUR,890,BHAGWATPUR,07359,"Makhdoompur Khas , Allahabad,Prayagraj,UTTAR P...",7823.424764,3.499521e+06,"POLYGON ((9096536.5803 2924031.6525, 9096288.3..."
95777,542786,RAJAPUR DEHMAHI,09,175,00890,943340,UTTAR PRADESH,Prayagraj,Allahabad,Rajapur Deh Maafi,...,9,0,None,890,KAURIHAR,00839,"Rajapur Deh Maafi , Allahabad,Prayagraj,UTTAR ...",5158.007395,1.289218e+06,"POLYGON ((9107223.341 2934658.6766, 9107223.05..."
95778,542787,KARAILA BAG,09,175,00890,943316,UTTAR PRADESH,Prayagraj,Allahabad,Kraila Bag,...,9,0,None,890,KAURIHAR,00839,"Kraila Bag , Allahabad,Prayagraj,UTTAR PRADESH",5403.368035,8.548021e+05,"POLYGON ((9106075.8825 2926266.2022, 9106445.4..."

In [15]:
up_urban = up_urban.dropna(subset=['vilnam_soi'])
up_urban = up_urban.loc[up_urban["stcode11"] == "09"]
up_urban["vilnam_soi"] = up_urban["vilnam_soi"].str.upper()
up_urban = up_urban[~up_urban["vilnam_soi"].str.contains("FOREST", na=False)]
up_urban = up_urban[~up_urban["vilnam_soi"].str.contains("RF", na=False)]
up_urban = up_urban[~up_urban["vilnam_soi"].str.contains("RESERVED FOREST", na=False)]
up_urban = up_urban[~up_urban["vilnam_soi"].str.contains(" RF", na=False)]
up_urban = up_urban[~up_urban["vilnam_soi"].str.contains("HILL", na=False)]
up_urban = up_urban[~up_urban["vilnam_soi"].str.contains("R F", na=False)]

up_urban

,objectid,vilnam_soi,stcode11,dtcode11,sdtcode11,vilcode11,stname,dtname,sdtname,vilname11,...,state_lgd,gp_code,gp_name,subdt_lgd,block_name,block_lgd,search_village,st_length(shape),st_area(shape),geometry
0,447787,KUCHELA,09,162,00841,148028,UTTAR PRADESH,Auraiya,Bidhuna,Kuchela,...,9,46778,KUKARKAT,841,ERWA KATRA,00864,"Kuchela , Bidhuna,Auraiya,UTTAR PRADESH",3353.915805,6.880540e+05,"POLYGON ((8835826.117 3111325.9917, 8835587.89..."
1,442064,BIRU NAGAR,09,146,00766,124650,UTTAR PRADESH,Agra,Agra,Brahmnagar,...,9,42852,AKBARPUR,766,BARAULI AHIR,00806,"Brahmnagar , Agra,Agra,UTTAR PRADESH",5294.335159,1.441254e+06,"POLYGON ((8693367.7743 3138457.6121, 8692999.5..."
2,442066,MALINAGLA,09,146,00766,124637,UTTAR PRADESH,Agra,Agra,Kalika Nagla,...,9,42882,KALIKA NAGLA,766,BARAULI AHIR,00806,"Kalika Nagla , Agra,Agra,UTTAR PRADESH",4437.474219,1.165989e+06,"POLYGON ((8687579.8113 3139642.746, 8686879.81..."
3,445126,SONGARHA,09,706,00914,169561,UTTAR PRADESH,Amethi,Amethi,Songarha,...,9,90974,AGRESAR,914,BHADAR,01581,"Songarha , Amethi,Amethi,UTTAR PRADESH",2347.873458,3.660032e+05,"POLYGON ((9131294.888 3012187.6331, 9130987.70..."
4,441464,PARBATPUR,09,146,00765,124463,UTTAR PRADESH,Agra,Etmadpur,Parbatpur,...,9,43162,HAZIPUR,765,KHANDAULI,00813,"Parbatpur , Etmadpur,Agra,UTTAR PRADESH",4836.618980,1.082456e+06,"POLYGON ((8682774.4653 3163422.9401, 8682560.9..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95774,542772,TIKARI,09,175,00890,161745,UTTAR PRADESH,Prayagraj,Allahabad,Tikri Kachhar,...,9,44927,TIKARI UPERHAR,890,BHAGWATPUR,07359,"Tikri Kachhar , Allahabad,Prayagraj,UTTAR PRADESH",7326.333876,2.263367e+06,"POLYGON ((9095918.7895 2937263.123, 9095362.13..."
95775,542776,TARAPUR (BHOPATPUR),09,175,00890,160724,UTTAR PRADESH,Prayagraj,Allahabad,Bhoopatpur Uparhar,...,9,72881,BHOPATPUR,890,BHAGWATPUR,07359,"Bhoopatpur Uparhar , Allahabad,Prayagraj,UTTAR...",5225.435382,1.729794e+06,"POLYGON ((9107327.329 2918701.8091, 9105978.58..."
95776,542782,MAKHANPUR,09,175,00890,160719,UTTAR PRADESH,Prayagraj,Allahabad,Makhdoompur Khas,...,9,72912,MAQDOOM PUR,890,BHAGWATPUR,07359,"Makhdoompur Khas , Allahabad,Prayagraj,UTTAR P...",7823.424764,3.499521e+06,"POLYGON ((9096536.5803 2924031.6525, 9096288.3..."
95777,542786,RAJAPUR DEHMAHI,09,175,00890,943340,UTTAR PRADESH,Prayagraj,Allahabad,Rajapur Deh Maafi,...,9,0,None,890,KAURIHAR,00839,"Rajapur Deh Maafi , Allahabad,Prayagraj,UTTAR ...",5158.007395,1.289218e+06,"POLYGON ((9107223.341 2934658.6766, 9107223.05..."
95778,542787,KARAILA BAG,09,175,00890,943316,UTTAR PRADESH,Prayagraj,Allahabad,Kraila Bag,...,9,0,None,890,KAURIHAR,00839,"Kraila Bag , Allahabad,Prayagraj,UTTAR PRADESH",5403.368035,8.548021e+05,"POLYGON ((9106075.8825 2926266.2022, 9106445.4..."

In [16]:
# https://en.wikipedia.org/wiki/List_of_urban_agglomerations_in_Uttar_Pradesh
urban_filter = ['kanpur','lucknow','ghaziabad','agra','varanasi','meerut','prayagraj','bareilly','aligarh','gorakhpur','ayodhya', 'jhansi', 'muzaffarnagar', 
                'mathura','rampur','shahjahanpur','Farrukhabad','mirzapur','bulandshahr','hardoi','orai','sitapur','modinagar','lakhimpur','hathras','banda','pilibhit','khurja','gonda','mainpuri','etah','ghazipur','sultanpur',
                'azamgarh','ballia' ,'(NPP)','(M Corp.)','(NP)','(OG)','(CB)','(CT)']
filtered_gdf = up_urban[up_urban['vilname11'].str.contains('|'.join(urban_filter), na=False)]
filtered_gdf

/var/folders/4r/12d0sssd0mdbgwbrthd30jk40000gn/T/ipykernel_38516/2494932214.py:5: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  filtered_gdf = up_urban[up_urban['vilname11'].str.contains('|'.join(urban_filter), na=False)]

,objectid,vilnam_soi,stcode11,dtcode11,sdtcode11,vilcode11,stname,dtname,sdtname,vilname11,...,state_lgd,gp_code,gp_name,subdt_lgd,block_name,block_lgd,search_village,st_length(shape),st_area(shape),geometry
99,441157,KALWARI,09,146,00766,124692,UTTAR PRADESH,Agra,Agra,Kalwari (CT),...,9,42915,KALWARI,766,BICHPURI,00807,"Kalwari (CT) , Agra,Agra,UTTAR PRADESH",7572.232960,3.233625e+06,"POLYGON ((8677056.6268 3147084.18, 8676677.782..."
147,441204,DHANAULI,09,146,00766,124698,UTTAR PRADESH,Agra,Agra,Dhanauli (CT),...,9,241772,DHANAULI,766,BICHPURI,00807,"Dhanauli (CT) , Agra,Agra,UTTAR PRADESH",13227.480482,9.285302e+06,"POLYGON ((8678294.5125 3142979.2065, 8677617.9..."
153,441210,AZIZPUR,09,146,00766,124697,UTTAR PRADESH,Agra,Agra,Azizpur (CT),...,9,274049,AZIZPUR,766,BICHPURI,00807,"Azizpur (CT) , Agra,Agra,UTTAR PRADESH",6170.711891,1.808432e+06,"POLYGON ((8680514.2175 3140563.4555, 8680747.2..."
195,441252,BESRAMPUR,09,146,00768,124945,UTTAR PRADESH,Agra,Kheragarh,Bishrampur,...,9,43198,BISHRAMPUR,768,KHERAGARH,00814,"Bishrampur , Kheragarh,Agra,UTTAR PRADESH",7137.784996,2.408859e+06,"POLYGON ((8669533.8921 3125052.8086, 8669219.5..."
211,441268,SIKRI,09,146,00767,800808,UTTAR PRADESH,Agra,Kiraoli,Fatehpur Sikri (NPP),...,9,0,None,767,FATEHPUR SIKRI,00810,"Fatehpur Sikri (NPP) , Kiraoli,Agra,UTTAR PRADESH",19001.820920,1.375611e+07,"POLYGON ((8645887.743 3137489.6092, 8644707.15..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95609,542562,KOTWA,09,197,00996,209755,UTTAR PRADESH,Varanasi,Sadar,Kotwa (CT),...,9,243378,KOTAWA,996,KASHI VIDYAPEETH,01621,"Kotwa (CT) , Sadar,Varanasi,UTTAR PRADESH",9054.014162,2.770890e+06,"POLYGON ((9232399.0758 2918694.6444, 9231114.1..."
95637,542590,CHHITAWNI,09,197,00996,209735,UTTAR PRADESH,Varanasi,Sadar,Chhitauni (CT),...,9,93402,CHITOUNI KOT,996,KASHI VIDYAPEETH,01621,"Chhitauni (CT) , Sadar,Varanasi,UTTAR PRADESH",6991.195967,2.765621e+06,"POLYGON ((9232868.6459 2916494.5935, 9232330.6..."
95653,542604,KORUTT,09,197,00996,209752,UTTAR PRADESH,Varanasi,Sadar,Kotwa (CT),...,9,0,None,996,ARAJILINE,01616,"Kotwa (CT) , Sadar,Varanasi,UTTAR PRADESH",17753.005254,1.172267e+07,"POLYGON ((9228292.2852 2921015.6737, 9227880.2..."
95684,542636,DEORAI,09,197,00995,208866,UTTAR PRADESH,Varanasi,Pindra,Deorai,...,9,93298,BANTARI,995,CHOLAPUR,01619,"Deorai , Pindra,Varanasi,UTTAR PRADESH",2644.722887,3.556189e+05,"POLYGON ((9237759.592 2944165.0625, 9237388.99..."
95734,542687,VARANASI M. C. I.,09,197,00996,801235,UTTAR PRADESH,Varanasi,Sadar,Varanasi (M Corp.),...,9,0,None,996,HARAHUA,01620,"Varanasi (M Corp.) , Sadar,Varanasi,UTTAR PRADESH",67977.605308,8.757318e+07,"POLYGON ((9243752.5332 2922216.0228, 9243033.4..."

In [20]:
merged = filtered_gdf.merge(up_vil[['vilcode11']],left_on='vilcode11', right_on='vilcode11',how='left')

merged

,objectid,vilnam_soi,stcode11,dtcode11,sdtcode11,vilcode11,stname,dtname,sdtname,vilname11,...,state_lgd,gp_code,gp_name,subdt_lgd,block_name,block_lgd,search_village,st_length(shape),st_area(shape),geometry
0,441157,KALWARI,09,146,00766,124692,UTTAR PRADESH,Agra,Agra,Kalwari (CT),...,9,42915,KALWARI,766,BICHPURI,00807,"Kalwari (CT) , Agra,Agra,UTTAR PRADESH",7572.232960,3.233625e+06,"POLYGON ((8677056.6268 3147084.18, 8676677.782..."
1,441204,DHANAULI,09,146,00766,124698,UTTAR PRADESH,Agra,Agra,Dhanauli (CT),...,9,241772,DHANAULI,766,BICHPURI,00807,"Dhanauli (CT) , Agra,Agra,UTTAR PRADESH",13227.480482,9.285302e+06,"POLYGON ((8678294.5125 3142979.2065, 8677617.9..."
2,441210,AZIZPUR,09,146,00766,124697,UTTAR PRADESH,Agra,Agra,Azizpur (CT),...,9,274049,AZIZPUR,766,BICHPURI,00807,"Azizpur (CT) , Agra,Agra,UTTAR PRADESH",6170.711891,1.808432e+06,"POLYGON ((8680514.2175 3140563.4555, 8680747.2..."
3,441252,BESRAMPUR,09,146,00768,124945,UTTAR PRADESH,Agra,Kheragarh,Bishrampur,...,9,43198,BISHRAMPUR,768,KHERAGARH,00814,"Bishrampur , Kheragarh,Agra,UTTAR PRADESH",7137.784996,2.408859e+06,"POLYGON ((8669533.8921 3125052.8086, 8669219.5..."
4,441268,SIKRI,09,146,00767,800808,UTTAR PRADESH,Agra,Kiraoli,Fatehpur Sikri (NPP),...,9,0,None,767,FATEHPUR SIKRI,00810,"Fatehpur Sikri (NPP) , Kiraoli,Agra,UTTAR PRADESH",19001.820920,1.375611e+07,"POLYGON ((8645887.743 3137489.6092, 8644707.15..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,542562,KOTWA,09,197,00996,209755,UTTAR PRADESH,Varanasi,Sadar,Kotwa (CT),...,9,243378,KOTAWA,996,KASHI VIDYAPEETH,01621,"Kotwa (CT) , Sadar,Varanasi,UTTAR PRADESH",9054.014162,2.770890e+06,"POLYGON ((9232399.0758 2918694.6444, 9231114.1..."
1613,542590,CHHITAWNI,09,197,00996,209735,UTTAR PRADESH,Varanasi,Sadar,Chhitauni (CT),...,9,93402,CHITOUNI KOT,996,KASHI VIDYAPEETH,01621,"Chhitauni (CT) , Sadar,Varanasi,UTTAR PRADESH",6991.195967,2.765621e+06,"POLYGON ((9232868.6459 2916494.5935, 9232330.6..."
1614,542604,KORUTT,09,197,00996,209752,UTTAR PRADESH,Varanasi,Sadar,Kotwa (CT),...,9,0,None,996,ARAJILINE,01616,"Kotwa (CT) , Sadar,Varanasi,UTTAR PRADESH",17753.005254,1.172267e+07,"POLYGON ((9228292.2852 2921015.6737, 9227880.2..."
1615,542636,DEORAI,09,197,00995,208866,UTTAR PRADESH,Varanasi,Pindra,Deorai,...,9,93298,BANTARI,995,CHOLAPUR,01619,"Deorai , Pindra,Varanasi,UTTAR PRADESH",2644.722887,3.556189e+05,"POLYGON ((9237759.592 2944165.0625, 9237388.99..."
1616,542687,VARANASI M. C. I.,09,197,00996,801235,UTTAR PRADESH,Varanasi,Sadar,Varanasi (M Corp.),...,9,0,None,996,HARAHUA,01620,"Varanasi (M Corp.) , Sadar,Varanasi,UTTAR PRADESH",67977.605308,8.757318e+07,"POLYGON ((9243752.5332 2922216.0228, 9243033.4..."

In [21]:
merged = merged.drop('vilcode11',axis=1)
final_gdf = gpd.GeoDataFrame(merged,geometry='geometry')
final_gdf.to_file("/Users/stephensmathew/cdl_rep/flood-data-ecosystem-UP/Maps/up_ids-drr_shapefiles/up_urban_final.geojson")

In [3]:
import os

# Use current working directory in Jupyter
repo_root = os.path.dirname(
    os.path.dirname(
        os.path.dirname(os.getcwd())
    )
)

print("Repo root (from Jupyter):", repo_root)

Repo root (from Jupyter): /Users/stephensmathew/cdl_rep/flood-data-ecosystem-UP